version: '3'

services:
# Dependency Services
  db_mysql: # MySQL Server
    build:
      context: .
      dockerfile: Dockerfile.db
    ports: # expose databse ports - ONLY DO THIS IN DEV ENV
      - 3306:3306
    volumes:
      - db_mysql:/var/lib/mysql

  redis: # Redis Server used for Session Caching
    image: 'redis:alpine'
    command: redis-server --requirepass yourpasswordkkfkfa

# Application Servers
  users_microservice:
    build:
      context: ../backend/users_microservice
      dockerfile: ../../infrastructure/Dockerfile.users
    volumes:
      - ../backend/users_microservice:/app
    ports:
      - 8080:8080

  challenges_microservice:
    build:
      context: ../backend/challenges_microservice
      dockerfile: ../../infrastructure/Dockerfile.challenges
    volumes:
      - ../backend/challenges_microservice:/app
    ports:
      - 8000:8000

  frontend: # Server for fully client side ReactJS application
    build:
      context: ../frontend
      dockerfile: ../infrastructure/Dockerfile.frontend
    volumes:
      - ../frontend:/app
      - /app/node_modules
    ports:
      - 80:5173

volumes:
  db_mysql: