FROM --platform=linux/amd64 python:3.11

WORKDIR /app

COPY . .
RUN pip install --no-cache-dir -r requirements.txt

ENV DB_HOST="db_marley"
ENV CACHE_HOST="redis"

EXPOSE 8080

CMD python3 -m uvicorn http_server:app --reload --host 0.0.0.0 --port 8080