name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build and run Docker containers
      run: |
        cd infrastructure
        docker compose up --build -d

    - name: Wait for services to be up
      run: sleep 20

    - name: Install dependencies
      run: |
        cd backend/challenges_microservice
        pip install -r requirements.txt

    - name: Run tests
      run: |
        cd backend/challenges_microservice
        python3 -m pytest
