name: Run Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build and Run Docker Containers
      run: |
        cd infrastructure
        docker compose up --build -d

    - name: Install Users Microservice Dependencies
      run: |
        cd backend/users_microservice
        pip install -r requirements.txt

    - name: Run Users Microservice Tests
      run: |
        cd backend/users_microservice
        python3 -m pytest

    - name: Install Challenges Microservice Dependencies
      run: |
        cd backend/challenges_microservice
        pip install -r requirements.txt

    - name: Run Challenges Microservice Tests
      run: |
        cd backend/challenges_microservice
        python3 -m pytest
